---
title: "gecon_chile_v1"
output: html_document
date: "2024-05-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
print(R.version.string)

rm(list = ls())
setwd("~/proyectos/equilibrio_general")
# Loading gEcon.iosam (and gEcon) package
library(gEcon.iosam)
library (pracma)
```

## Importacion de datos



```{r }
chile_sam <- read.csv("macro_sam_2008_simp.csv", row.names=1)
rows1<-c( 'Actprim', 'Actmanu', 'Actserv', 'Prodprim', 'Prodmanu', 'Prodserv', 'Trabajo', 'Capital', 'Hogares',
          'Empresas', 'Gobierno', 'Cont_soc', 'Pres_soc', 'Imp_dir', 'IVA', 'SI', 'Total')

flow1<- iosam(as.matrix(chile_sam),  nproducts=c(3,3),
              rows=rows1)


summary(flow1)

acts<-c('Actprim', 'Actmanu', 'Actserv')
sam_prod<-c('Prodprim', 'Prodmanu', 'Prodserv')

sam_prod_sp<-c('Prodmanu', 'Prodserv')
```

## Building model from the .gcn file




```{r }


model <- make_model("cge_calib_chile_2008_simpl.gcn")


model <- set_free_par(model, c(omega=1.1,
                               k_total_data=flow1['Total', 'Capital'],
                               par_k_h=flow1['Hogares', 'Capital']/flow1['Total', 'Capital'],
                               par_k_f=flow1['Empresas', 'Capital']/flow1['Total', 'Capital'],
                               par_k_g=flow1['Gobierno', 'Capital']/flow1['Total', 'Capital'],

                               l_total_data=flow1['Total', 'Trabajo'],

                               por_cont_soc_f=flow1['Empresas', 'Cont_soc']/flow1['Total', 'Cont_soc'],
                               por_cont_soc_g=flow1['Gobierno', 'Cont_soc']/flow1['Total', 'Cont_soc'],
                               por_pres_soc_f=flow1[ 'Pres_soc', 'Empresas']/flow1['Total', 'Empresas'],
                               por_pres_soc_g=flow1['Pres_soc', 'Gobierno' ]/flow1['Total', 'Gobierno'],
                              pit=flow1['Imp_dir','Hogares' ]/(flow1['Hogares', 'Trabajo']+flow1['Hogares', 'Capital']), 
                               fit=flow1['Imp_dir','Empresas' ]/flow1['Empresas', 'Capital'],
                               por_sav=flow1['SI','Hogares' ]/flow1['Hogares', 'Total'],
                               por_sav_f=flow1['SI','Empresas' ]/flow1['Empresas', 'Total'],
                               por_sav_g=flow1['SI','Gobierno' ]/flow1['Gobierno', 'Total'],
                               por_cont=flow1['Cont_soc','Hogares' ]/flow1['Hogares', 'Total'],
                               por_tremp=flow1['Hogares','Empresas' ]/flow1['Empresas', 'Total'],
                               por_trgov=flow1['Hogares','Gobierno' ]/flow1['Gobierno', 'Total'],
                               get_flow_values(flow1[sam_prod_sp, 'Hogares'], "d_data", sam_prod_sp),
                               #get_flow_values(flow1['Trabajo', acts], "l_data", acts),
                              l_data__Prodprim__Actprim=flow1['Trabajo', 'Actprim'],
l_data__Prodmanu__Actprim=0,
l_data__Prodserv__Actprim=0,
l_data__Prodprim__Actmanu=0,
l_data__Prodmanu__Actmanu=flow1['Trabajo', 'Actmanu'],
l_data__Prodserv__Actmanu=0,
l_data__Prodprim__Actserv=0,
l_data__Prodmanu__Actserv=0,
l_data__Prodserv__Actserv=flow1['Trabajo', 'Actserv'],
                          get_flow_values(flow1['IVA',sam_prod]/(flow1['Total',sam_prod]-flow1['IVA',sam_prod]), "vat",sam_prod),
                               get_flow_values(flow1[sam_prod, 'Gobierno'], "data_gg_p",sam_prod),
                               get_flow_values(flow1[acts,sam_prod], "data_prod_s", acts, sam_prod)
                               
))


model <- steady_state(model, calibration=T)
```


# Listado de parametros


alpha__Prodprim                 0.577
alpha__Prodmanu                 0.063
alpha__Prodserv                 0.168


```{r}

n <- length(sam_prod)
m<-length(acts)

g_p=2.5
g_o=2

gp_prim=3.001
gp_manu=2.02*0+2.02379871630269
gp_serv=2*0+2.00018954448853

bl_prim=0.416
bl_manu=0.49*0+0.490342131
bl_serv=0.491*0+0.491338513

chico=0.000002

listcalib<-c(#get_flow_values(rep(0.3683438, n), "alpha", sam_prod),
             alpha__Prodprim=0.3,              
            alpha__Prodmanu=0.6,                 
            alpha__Prodserv=0.02,                 

             
             get_flow_values(matrix(1-bl_prim, n), "beta_k", sam_prod, "Actprim"),
             get_flow_values(matrix(1-bl_manu, n), "beta_k", sam_prod, "Actmanu"),
             get_flow_values(matrix(1-bl_serv, n), "beta_k", sam_prod, "Actserv"),
             
             get_flow_values(matrix(bl_prim, n,m), "beta_l", sam_prod, "Actprim"),
             get_flow_values(matrix(bl_manu, n,m), "beta_l", sam_prod, "Actmanu"),
             get_flow_values(matrix(bl_serv, n,m), "beta_l", sam_prod, "Actserv"),
             
             gamma__Prodprim__Actprim=gp_prim, gamma__Prodmanu__Actprim=g_o, gamma__Prodserv__Actprim=g_o,
             gamma__Prodprim__Actmanu=g_o, gamma__Prodmanu__Actmanu=gp_manu, gamma__Prodserv__Actmanu=g_o,
             gamma__Prodprim__Actserv=g_o, gamma__Prodmanu__Actserv=g_o, gamma__Prodserv__Actserv=gp_serv
             



             
)


varlist=list(#lambda__CONSUMER_1=0.8,
             p_k=1,
             U=1,

             BTINC=flow1['Total', 'Hogares' ],
             CONT_SOC=flow1['Total', 'Cont_soc' ],
             CONT_SOC_F=flow1['Empresas', 'Cont_soc' ],
             CONT_SOC_G=flow1['Gobierno', 'Cont_soc' ],
             DIR_T=flow1['Total', 'Imp_dir' ],
             GTO_G=flow1['Total', 'Gobierno' ],
             INC=flow1['Total', 'Hogares' ]- flow1['Imp_dir', 'Hogares' ],
             ING_F=flow1['Total', 'Empresas' ],
             ING_GOB=flow1['Total', 'Gobierno' ],
             K_h=flow1['Hogares', 'Capital' ], K_f=flow1['Empresas', 'Capital' ], K_g=flow1['Gobierno', 'Capital' ], 
             L_h=flow1['Total', 'Trabajo' ],
             PIT_base=flow1['Hogares', 'Trabajo']+ flow1['Hogares', 'Capital'],
             PREST_SOC=flow1['Total', 'Pres_soc' ],
             PREST_SOC_F=flow1[ 'Pres_soc','Empresas' ],
             PREST_SOC_G=flow1['Pres_soc', 'Gobierno' ],

             SAV=flow1['SI', 'Hogares' ],
             SAV_F=flow1['SI', 'Empresas' ],
             SAV_TOT=flow1['SI', 'Total' ],
             SAV_G=flow1['SI', 'Gobierno' ],
             TOTAL_TAX=flow1['Total', 'Imp_dir' ]+flow1['Total', 'IVA' ],
             TR_EMP=flow1['Hogares', 'Empresas' ],
             TR_GOV=flow1['Hogares', 'Gobierno' ],
             
             VAT=flow1['Total', 'IVA' ],
             p__Prodprim=1, p__Prodmanu=1, p__Prodserv=1, # Precios de los bienes
             pi__Actprim=0, pi__Actmanu=0, pi__Actserv=0, #Utilidades de las industrias
             
             D__Prodprim=flow1['Prodprim', 'Hogares' ]/(1+flow1['IVA','Prodprim']/(flow1['Total','Prodprim']-flow1['IVA','Prodprim'])), 
             D__Prodmanu=flow1['Prodmanu', 'Hogares']/(1+flow1['IVA','Prodmanu']/(flow1['Total','Prodmanu']-flow1['IVA','Prodmanu'])), 
             D__Prodserv=flow1['Prodserv', 'Hogares' ]/(1+flow1['IVA','Prodserv']/(flow1['Total','Prodserv']-flow1['IVA','Prodserv'])), #Demanda de los hogares


             DA__Prodprim=flow1['Prodprim', 'Total' ], 
             DA__Prodmanu=flow1['Prodmanu', 'Total' ], 
             DA__Prodserv=flow1['Prodserv', 'Total' ], #Demanda agregada por producto
             
             GG__Prodprim=flow1['Prodprim', 'Gobierno' ]/(1+flow1['IVA','Prodprim']/(flow1['Total','Prodprim']-flow1['IVA','Prodprim'])), 
             GG__Prodmanu=flow1['Prodmanu', 'Gobierno' ]/(1+flow1['IVA','Prodmanu']/(flow1['Total','Prodmanu']-flow1['IVA','Prodmanu'])), 
             GG__Prodserv=flow1['Prodserv', 'Gobierno' ]/(1+flow1['IVA','Prodserv']/(flow1['Total','Prodserv']-flow1['IVA','Prodserv'])), #Gasto de gobierno
             I__Prodprim=flow1['Prodprim', 'SI' ]/(1+flow1['IVA','Prodprim']/(flow1['Total','Prodprim']-flow1['IVA','Prodprim'])), 
             I__Prodmanu=flow1['Prodmanu', 'SI' ]/(1+flow1['IVA','Prodmanu']/(flow1['Total','Prodmanu']-flow1['IVA','Prodmanu'])), 
             I__Prodserv=flow1['Prodserv', 'SI' ]/(1+flow1['IVA','Prodserv']/(flow1['Total','Prodserv']-flow1['IVA','Prodserv'])), #Inversion
             #Capital usado en cada producto en cada actividad
             
             K__Prodprim__Actprim=flow1['Capital','Actprim'], K__Prodprim__Actmanu=chico, K__Prodprim__Actserv=chico,
             K__Prodmanu__Actprim=chico, K__Prodmanu__Actmanu=flow1['Capital','Actmanu'], K__Prodmanu__Actserv=chico,
             K__Prodserv__Actprim=chico, K__Prodserv__Actmanu=chico, K__Prodserv__Actserv=flow1['Capital','Actserv'],
             #Trabajo usado en cada producto en cada actividad
             L__Prodprim__Actprim=flow1['Trabajo','Actprim'], L__Prodprim__Actmanu=chico, L__Prodprim__Actserv=chico, 
             L__Prodmanu__Actprim=chico, L__Prodmanu__Actmanu=flow1['Trabajo','Actmanu'], L__Prodmanu__Actserv=chico, 
             L__Prodserv__Actprim=chico, L__Prodserv__Actmanu=chico, L__Prodserv__Actserv=flow1['Trabajo','Actserv'],
            
             OA__Prodprim=flow1['Total', 'Prodprim' ]-flow1['IVA', 'Prodprim' ], OA__Prodmanu=flow1['Total', 'Prodmanu' ]-flow1['IVA', 'Prodmanu' ], OA__Prodserv=flow1['Total', 'Prodserv' ]-flow1['IVA', 'Prodserv' ], #Oferta agregada por producto
             
          
             
             # Produccion por actividad
             Y__Prodprim__Actprim=flow1['Actprim', 'Prodprim' ],  Y__Prodprim__Actmanu=flow1['Actmanu', 'Prodprim' ], Y__Prodprim__Actserv=flow1['Actserv', 'Prodprim' ],
             Y__Prodmanu__Actprim=flow1['Actprim', 'Prodmanu' ], Y__Prodmanu__Actmanu=flow1['Actmanu', 'Prodmanu' ], Y__Prodmanu__Actserv=flow1['Actserv', 'Prodmanu' ],
             Y__Prodserv__Actprim=flow1['Actprim', 'Prodserv' ], Y__Prodserv__Actmanu=flow1['Actmanu', 'Prodserv' ], Y__Prodserv__Actserv=flow1['Actserv', 'Prodserv' ]
             
)



```



# Generacion del modelo calibrado

```{r}
model <- initval_calibr_par(model, listcalib)

model <- initval_var(model, varlist)

model <- steady_state(model, calibration=T, use_jac=T, last_solver_iter =F,
                      options_list=list(method="Newton",global="gline", 
                                        max_iter=300,tol=1e-06, xscalm="auto", xtol=1e-6)
)
```

# Estadisticas de residuos

```{r}
get_residuals(model)
Norm(model@init_residual_vector)
Norm(model@residual_vector)

```

```{r}
model@residual_vector[c(37)] # Residuo de la funcion de utilidad
var_info(model,variables=c('U', 'lambda__CONSUMER_1')) 
```
[1] 0.05499548 con omega=1.1 y alfa=0.2 y U=0.1
[1] 0.3549955 con omega=1.1 y alfa=0.2 y U=0.4
[1] 0.4549955 con omega=1.1 y alfa=0.2 y U=0.5
[1] 0.018 con omega=1.1 y alfa=0.2 y U=1


```{r}
round(model@residual_vector[c(47, 51, 55)], digits = 6) #Estos son los residuos de las funciones de produccion

```
[1] 0.006135  0.000000 -0.004836 con param excel


```{r}
round(model@residual_vector[c(1, 57, 58, 56, 37)], digits=4 )
list_eq(model, eq_idx = c(1, 57, 58, 56, 37))


```
```{r}
var_info(model,variables=c('p__Prodprim', 'K__Prodprim__Actprim', 'L__Prodprim__Actprim')) 
#get_par_values(model,parameters =c('beta_l__Prodprim__Actprim', 'gamma__Prodprim__Actprim', 'beta_k__Prodprim__Actprim'))
```

No aparecen los capitales de cada sector K<s>, estan representados por sus productos

```{r}
var_info(model,variables=c('K_h', 'K_f', 'K_g', 'K__Prodprim__Actprim', 'K__Prodprim__Actmanu', 'K__Prodprim__Actserv', 'K__Prodmanu__Actprim', 'K__Prodmanu__Actmanu', 'K__Prodmanu__Actserv', 'K__Prodserv__Actprim', 'K__Prodserv__Actmanu', 'K__Prodserv__Actserv'))

```

```{r}
list_calibr_eq(model, c(30))
```


 
# Estadisticas de valores obtenidos

```{r}
var_info(model,variables=c('p_k', 'p__Prodprim', 'p__Prodmanu', 'p__Prodserv'))

var_info(model,variables=c('pi__Actserv', 'pi__Actprim', 'pi__Actmanu'))


var_info(model,variables=c("OA__Prodmanu", "Y__Prodmanu__Actmanu", "Y__Prodmanu__Actprim", "Y__Prodmanu__Actserv",'DA__Prodmanu',
                           "D__Prodmanu","GG__Prodmanu", 'I__Prodmanu', 'p__Prodmanu' ))

var_info(model,variables=c("OA__Prodprim", "Y__Prodprim__Actmanu", "Y__Prodprim__Actprim", "Y__Prodprim__Actserv",'DA__Prodprim',
                           "D__Prodprim","GG__Prodprim", 'I__Prodprim',  'p__Prodprim' ))

var_info(model,variables=c("OA__Prodserv", "Y__Prodserv__Actmanu", "Y__Prodserv__Actprim", "Y__Prodserv__Actserv", 'DA__Prodserv',
                           "D__Prodserv","GG__Prodserv", 'I__Prodserv', 'p__Prodserv' ))

var_info(model,variables=c('K__Prodprim__Actprim', 'K__Prodmanu__Actmanu', 'K__Prodserv__Actserv' ))

var_info(model,variables=c('VAT', 'DIR_T' ))


```

```{r}
get_par_values(model)
```


```{r}
list_calibr_eq(model, eq_idx = NULL)

```

```{r}
list_eq(model, eq_idx = NULL)
```


```{r}
library (pracma)
Norm(model@init_residual_vector)
Norm(model@residual_vector)

```



