library(gEcon.iosam)
model <- make_model("cge_calib_chile_2008_simpl.gcn")
sink("orig_debug.txt")
print("--- VARIABLES ---")
vi <- var_info(model, all = TRUE)
print(vi)
print("--- EQUATIONS ---")
list_eq(model)
sink()
