library(gEcon.iosam)
setwd('d:/francisco.henriquez/Mis documentos/proyectos/equilibrio_general/eq_general')
source('gecon_chile_simpl_debug.R')
cat('Eq 28: ', model@equations[28], '\n')
cat('Eq 29: ', model@equations[29], '\n')
