library(gEcon.iosam)
setwd('d:/francisco.henriquez/Mis documentos/proyectos/equilibrio_general/eq_general')
source('gecon_chile_simpl_debug.R')
get_par_values(model)
cat('\n\nFinal variable values:\n')
print(model@solution)
