p_names <- c("p1", "p2", "p3")
s_names <- c("s1", "s2")
mat <- matrix(1:6, nrow=3, dimnames=list(p_names, s_names))
grid <- expand.grid(p_names, s_names)
names <- paste0("Var__", grid$Var1, "__", grid$Var2)
print("Matrix values as.numeric:")
print(as.numeric(mat))
print("Names:")
print(names)
